/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#00302b",
        "on-secondary": "#003732",
        "tertiary": "#bcc7de",
        "inverse-surface": "#d3e4fe",
        "on-surface": "#d3e4fe",
        "surface-tint": "#b4c5ff",
        "tertiary-container": "#636e83",
        "surface-bright": "#2a3a4f",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#bcc7de",
        "error": "#ffb4ab",
        "surface": "#031427",
        "outline-variant": "#434655",
        "inverse-primary": "#0053db",
        "surface-variant": "#26364a",
        "outline": "#8d90a0",
        "on-surface-variant": "#c3c6d7",
        "on-primary-container": "#eeefff",
        "surface-container-lowest": "#000f21",
        "surface-container-high": "#1b2b3f",
        "on-primary-fixed": "#00174b",
        "primary": "#b4c5ff",
        "on-secondary-fixed-variant": "#005049",
        "on-secondary-fixed": "#00201d",
        "primary-container": "#2563eb",
        "primary-fixed": "#dbe1ff",
        "on-primary": "#002a78",
        "on-tertiary-fixed-variant": "#3c475a",
        "tertiary-fixed": "#d8e3fb",
        "background": "#031427",
        "on-tertiary-fixed": "#111c2d",
        "secondary": "#6bd8cb",
        "on-tertiary": "#263143",
        "secondary-container": "#29a195",
        "primary-fixed-dim": "#b4c5ff",
        "on-error": "#690005",
        "secondary-fixed": "#89f5e7",
        "on-tertiary-container": "#ecf1ff",
        "inverse-on-surface": "#213145",
        "on-background": "#d3e4fe",
        "surface-container-low": "#0b1c30",
        "surface-dim": "#031427",
        "secondary-fixed-dim": "#6bd8cb",
        "surface-container-highest": "#26364a",
        "on-primary-fixed-variant": "#003ea8",
        "on-error-container": "#ffdad6",
        "surface-container": "#102034"
      },
    },
  },
  plugins: [],
}
